#LEVANTANDO UNA NUEVA IMAGEN

FROM nginx:latest

#Copiamos nuestro file index.html al container de Nginx
COPY index.html C:\Users\Facu\Desktop\DH\DHContenido\Infra1\Docker\index

# Se puede personalizar la configuracion
#COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

